main: ${group}.${mainClass}
name: ${name}
version: ${version}
api-version: 1.13
load: STARTUP
authors: [${authors}]
description: ${description}
website: ${website}
depend: [${depend}]
softdepend: [${softDepend}]
loadbefore: [${loadBefore}]